apiVersion: extensions/v1beta1
metadata:
  name: game
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      name: game
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: runseb/2048
